spring:
#  boot:
#    admin:
#      mail:
#        to: ${spring.mail.username}, test@yandex.ru
#        from: ${spring.mail.username}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    template:
      routing-key: mailbox
      exchange: amq.topic
  mail:
    host: smtp.gmail.com
    port: 587
    username: aidarsinetov@gmail.com
    password: qellwcocmlmrzstn
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtp
  jms:
    pub-sub-domain: false
    listener:
      acknowledge-mode: auto

server:
  port: 8090


#logging:
#  level:
#    root: DEBUG